POST http://localhost:8080/reserve
Content-Type: application/json

{
"flatId": 1,
"timeCell": 2,
"tenantId": 47
}

###

PATCH http://localhost:8080/approve
Content-Type: application/json

{
  "flatId": 1,
  "timeCell": 2
}

###

PATCH http://localhost:8080/cancel
Content-Type: application/json

{
"flatId": 1,
"timeCell": 2
}

###
POST http://localhost:8080/reserve
Content-Type: application/json

{
  "flatId": 2,
  "timeCell": 1,
  "tenantId": 32
}

###

PATCH http://localhost:8080/reject
Content-Type: application/json

{
  "flatId": 2,
  "timeCell": 1
}

